version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: npm run build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
            
      
  deploy:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: v1-awscli
      - run:
          name: Install awscli
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli
      - save_cache:
          key: v1-awscli
          paths:
            - "venv"
      - run:
          name: Deploy
          command: |
            aws s3 sync build/ s3://react-demo.dnx.host --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                